spring:
  application:
    name: BANNERS-SERVICE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/banners
    username: postgres
    password: admin
server:
  port: 8080
